# Generated by Django 3.2.4 on 2021-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=12, null=True)),
                ('last_name', models.CharField(blank=True, max_length=12, null=True)),
                ('Age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=12, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('Courses', models.CharField(blank=True, max_length=14, null=True)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('Salary', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Lesson_Duration', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
