# Generated by Django 3.2.4 on 2021-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Courses',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Email_Address',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Lesson_Duration',
            new_name='lesson_duration',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='Salary',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
