# Generated by Django 3.2.4 on 2021-08-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_auto_20210819_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='courses',
        ),
        migrations.AddField(
            model_name='trainer',
            name='cv',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
