# Generated by Django 3.2.4 on 2021-09-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0003_auto_20210821_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='phone_number',
        ),
    ]
