# Generated by Django 3.2.4 on 2021-08-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesform',
            name='name',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
