# Generated by Django 3.2.4 on 2021-08-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_coursesform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesform',
            name='course_schedule',
        ),
    ]
