# Generated by Django 3.2.4 on 2021-08-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('roll_number', models.PositiveSmallIntegerField(null=True)),
                ('student_id', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('city_name', models.CharField(max_length=15, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('date_of_birth', models.DateField(max_length=20, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('date_of_enrollment', models.DateField(null=True)),
                ('medical_report', models.FileField(null=True, upload_to='documents/')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('languages', models.CharField(choices=[('L', 'Luganda'), ('E', 'English'), ('K', 'Kiswahili'), ('K', 'Kinyarwanda')], max_length=6, null=True)),
            ],
        ),
    ]
